dist: xenial
services: docker
language: bash
addons:
    apt:
        config:
            retries: true
        update: true
        packages:
            - jq
            - rpm2cpio
            - cpio
env:
    global:
        - VERSION=4.0.0
        - REPO=multiarch/qemu-user-static
        - PACKAGE_URI="https://kojipkgs.fedoraproject.org/packages/qemu/4.0.0/1.fc31/x86_64/qemu-user-static-4.0.0-1.fc31.x86_64.rpm"
        - PACKAGE_FILENAME=$(basename "$PACKAGE_URI")
before_script:
    - wget --content-disposition $PACKAGE_URI
    - rpm2cpio $PACKAGE_FILENAME | cpio -dimv
script:
    - ./generate_tarballs.sh
    - |
      if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
          ./publish.sh -v "$VERSION" -t "$GITHUB_TOKEN" -r "$REPO" && \
              ./update.sh -v "$VERSION" -r "$REPO"
      fi
after_success:
    - |
      if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && \
              docker push $REPO
      fi
