services: docker
language: bash
addons:
  apt:
    packages:
      - pass
env:
    global:
        - VERSION=3.1.0-2
        - REPO=multiarch/qemu-user-static
        - PACKAGE_URI="https://kojipkgs.fedoraproject.org/packages/qemu/3.1.0/2.fc30/x86_64/qemu-user-static-3.1.0-2.fc30.x86_64.rpm"
        - PACKAGE_FILENAME=qemu-user-static-3.1.0-2.fc30.x86_64.rpm
before_script:
    - sudo apt-get install jq rpm2cpio cpio
    - wget --content-disposition $PACKAGE_URI
    - rpm2cpio $PACKAGE_FILENAME | cpio -dimv
script:
    - ./generate_tarballs.sh
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./publish.sh -v "$VERSION" -t "$GITHUB_TOKEN" -r "$REPO"; fi
    - ./update.sh -v "$VERSION" -r "$REPO"
after_success:
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./deploy.sh; fi
